"""TileLang reimplementation of the Ascend C ``SparseAttnSharedkv`` operator.

This is a clean-room port that faithfully follows the Ascend C kernel
(`ops-transformer/.../sparse_attn_sharedkv/op_kernel`). The op fuses three
attention scenarios over a shared KV cache (N1=64 q-heads, N2=1 kv-head, D=512):

* scenario 1 -- **SWA**  : sliding-window attention over the uncompressed,
  page-attention ``ori_kv`` (win_left=127, win_right=0).
* scenario 2 -- **CFA**  : SWA + dense compressed attention over ``cmp_kv``.
* scenario 3 -- **SCFA** : SWA + sparse top-k compressed attention (the
  selected ``cmp_kv`` tokens are gathered via ``cmp_sparse_indices``).

Like the Ascend C kernel it runs in the MIX_AIC_1_2 layout: ``core_num`` AI
cores, each pairing one Cube unit (AIC) with two Vector lanes (AIV). Work is
distributed across cores by the companion metadata op (a ``[1024]`` int32
per-core ``(bn2, gS1, s2)`` range). The Cube unit runs the two matmuls
(Q@K^T, P@V) and the Vector lanes run scale / softmax / output-normalize,
overlapped through a cross-core software pipeline.

This file is built up incrementally (SWA first); see ``build_sparse_attn_sharedkv``.

SWA is written in the **auto-CV** style: a flat op sequence
(copy / gemm_v0 / T.tile.*) inside a runtime-bounded ``T.serial`` over this
core's metadata-assigned queries, with the cube/vector split, cross-core sync
and on-chip double-buffering all generated by the compiler
(TL_ASCEND_AUTO_CV_COMBINE / _CV_SYNC / _SYNC / MEMORY_PLANNING). There are NO
manual ``T.Scope``/``T.set_flag``/``T.set_cross_flag``/``T.annotate_address`` --
this mirrors the ``flash_attn_bhsd_auto_pipeline_h32_d512`` and
``sparse_flash_attn_gqa_pipeline`` templates and the paged
``sparse_flash_attn_pa`` reference. The public ABI (kernel argument order,
``out_idx``/``workspace_idx``) is unchanged so ``api.py`` is unchanged.

Notes on the adversarial-review fixes baked into this version:

* **L0 sizing** -- a flat ``kv_l1[128, 512]`` bf16 tile is 128KB and would
  fault MTE1 when fed to ``T.gemm_v0`` (L0A/L0B = 64KB, gemm_v0 does NOT
  auto-tile). The KV window is therefore gathered into two 64-row halves
  ``kv_lo``/``kv_hi`` (``[64, 512]`` = 64KB each). Q@K^T runs as two gemms
  (one per half) and P@V accumulates the 128-key contraction over the two
  halves (``init=True`` then ``init=False``) -- the validated split used by
  the working HEAD kernel and the flash template's ``n_num`` machinery.
* **GM handoff workspaces are single-buffered** -- ``ws_score``/``ws_p``/
  ``ws_o`` carry no ping-pong stage dim. Both auto-pipeline templates (and the
  paged reference) use one GM slot per core and let the compiler double-buffer
  the L1/UB/L0C tiles across pipeline stages; a constant-0-indexed ``[.,2,.]``
  workspace (as in the pre-fix draft) raced across overlapped queries.
* **Runtime-bounded ``T.serial`` query loop, NOT ``T.Pipelined``** -- the per-core
  query loop is ``for j in T.serial(0, n_local)`` with the ``if valid`` guard
  INSIDE. A data-dependent ``if`` directly inside ``T.Pipelined`` segfaults
  ``AscendMemoryPlanning`` under the auto-CV passes (HoistIfThenElse hoists it
  into a shape MemoryPlanning can't place); the validated ``sparse_flash_attn_pa``
  reference keeps the guard in a runtime ``T.serial`` loop and pipelines only a
  compile-time inner count. Cross-query overlap (T.Pipelined) is layered on next,
  once this compiles + matches numerically.
* **Per-query scalars materialized via ``T.alloc_var``** -- the loop-carried
  index math (b/s/t/s_global/ori_left and the gather offsets) is written into
  scalar vars once per iteration so it is not re-inlined (re-read from GM) on
  every use, restoring the scalar-pipe fix from commit 6b97576. The rebind
  idiom (``x = T.alloc_var(...); x = <expr>``; use bare ``x``) is the dialect's
  scalar-assignment form, confirmed by ``test_tilelang_ascend_language_alloc_var``.
* **Window mask is unconditional** -- the createvecindex+compare(LE)+select
  chain runs every iteration (matching the validated paged reference). For a
  full window the compare is all-true so the select is a numeric no-op; this
  removes the untested data-dependent ``if`` from the auto-pipelined body.
"""

import tilelang
from tilelang import language as T

# ---------------------------------------------------------------------------
# Compile-time defaults / layout constants.
# ---------------------------------------------------------------------------
DEFAULT_CORE_NUM = 24  # AIC cores (each drives 2 AIV lanes) -- MIX_AIC_1_2.
DEFAULT_BLOCK_I = 128  # KV tile width (s2 base block fed to one QK/PV step).

# Metadata ([1024] int32) FA-record layout, mirroring sparse_attn_sharedkv_metadata.h.
_SAS_META_SIZE = 1024
_FA_METADATA_SIZE = 8
_FA_CORE_ENABLE_INDEX = 0
_FA_BN2_START_INDEX = 1
_FA_M_START_INDEX = 2
_FA_S2_START_INDEX = 3
_FA_BN2_END_INDEX = 4
_FA_M_END_INDEX = 5
_FA_S2_END_INDEX = 6

# Auto cube/vector pipeline. The compiler splits the flat op sequence into a
# Cube program (gemm_v0) and a Vector program (T.tile.*), inserts the cross-core
# (Cube<->Vector) handshakes from the GM workspace read/write dependencies, and
# double-buffers across pipeline stages. Mirrors both template files.
pass_configs = {
    tilelang.PassConfigKey.TL_ASCEND_AUTO_CV_COMBINE: True,
    tilelang.PassConfigKey.TL_ASCEND_AUTO_CV_SYNC: True,
    tilelang.PassConfigKey.TL_ASCEND_AUTO_SYNC: True,
    tilelang.PassConfigKey.TL_ASCEND_MEMORY_PLANNING: True,
}

# Cache control: the kernel is parametrised heavily, keep JIT cache off to avoid
# stale binaries during development (matches the Ascend NPU pitfall guidance).
tilelang.disable_cache()
tilelang.cache.clear_cache()


def _check_dtypes(dtype: str) -> None:
    if dtype not in ("bfloat16", "float16"):
        raise ValueError(f"dtype must be bfloat16 or float16, got {dtype!r}")


def build_sparse_attn_sharedkv(
    *,
    batch: int,
    max_seq: int,
    total_tokens: int,
    ori_block_num: int,
    ori_block_size: int,
    ori_table_len: int,
    cmp_block_num: int,
    cmp_block_size: int,
    cmp_table_len: int,
    n_heads: int = 64,
    n_kv_heads: int = 1,
    head_dim: int = 512,
    topk_cmp: int = 512,
    cmp_ratio: int = 4,
    scenario: int = 3,
    ori_win_left: int = 127,
    softmax_scale: float = 0.04419417,
    dtype: str = "bfloat16",
    block_I: int = DEFAULT_BLOCK_I,
    core_num: int = DEFAULT_CORE_NUM,
    return_prim_func: bool = False,
):
    """JIT-compile the SparseAttnSharedkv kernel for one parameter set.

    Returns a ``tilelang.jit``-wrapped ``prim_func`` whose ABI is the 11 inputs
    / 2 outputs / 5 workspaces documented in ``api.py``.

    When ``return_prim_func`` is True the *uncompiled* ``tir.PrimFunc`` is
    returned instead (no bisheng), so codegen-only dumps can be obtained via
    ``tilelang.lower`` even when the device compile would fail.
    """
    _check_dtypes(dtype)
    assert n_heads == 64, "API constraint: n_heads must be 64"
    assert n_kv_heads == 1, "API constraint: n_kv_heads must be 1"
    assert head_dim == 512, "API constraint: head_dim must be 512"
    assert ori_win_left == 127, "API constraint: ori_win_left must be 127"
    assert topk_cmp >= 0
    assert topk_cmp % block_I == 0, "topk_cmp must be a multiple of block_I"
    assert scenario in (1, 2, 3), "scenario must be 1 (SWA), 2 (CFA) or 3 (SCFA)"
    assert batch > 0 and max_seq > 0 and total_tokens > 0
    assert ori_block_num > 0 and ori_block_size > 0 and ori_table_len > 0
    assert cmp_block_num > 0 and cmp_block_size > 0 and cmp_table_len > 0
    # The SWA gather loads the whole 128-key window as a single contiguous range
    # split into <=2 page segments PER 64-row half; for a 64-key sub-range to
    # cross at most ONE page boundary the page block must hold a full half-tile
    # (always true in practice: ori_block_size = 128 >= BI = 128 > BI_half = 64).
    assert ori_block_size >= block_I, "ori_block_size must be >= BI"

    gqa_group = n_heads // n_kv_heads  # 64 q-heads share 1 kv-head.
    BI = block_I  # 128
    BI_half = BI // 2  # 64 -- KV is loaded/gemm'd in two 64-row halves (L0 fit).
    D = head_dim  # 512
    accum_dtype = "float"
    indices_dtype = "int32"

    # ori sliding window spans <= ori_win_left+1 = 128 keys, i.e. exactly one BI
    # tile, so SWA is single-tile attention per query (no cross-tile flash loop).
    # NI_cmp = number of compressed KV tiles (0 for SWA); drives indices_shape.
    NI_cmp = topk_cmp // BI

    # Head split: each of the 2 AIV lanes owns v_block=32 of the 64 q-heads.
    H_per_block = gqa_group  # 64
    v_block = H_per_block // 2  # 32
    # UB needs >= 8 fp32 (32B) for the per-head scalar vectors.
    ub_len = max(32 // 4, v_block)  # 32
    mask_w = ((BI // 8 + 31) // 32) * 32  # uint8 mask row, 32B aligned (= 32).

    # ---- Tensor shapes (the kernel ABI). ----
    q_shape = [total_tokens, n_heads, D]
    out_shape = [total_tokens, n_heads, D]
    ori_kv_shape = [ori_block_num, ori_block_size, n_kv_heads, D]
    cmp_kv_shape = [cmp_block_num, cmp_block_size, n_kv_heads, D]
    ori_bt_shape = [batch, ori_table_len]
    cmp_bt_shape = [batch, cmp_table_len]
    indices_shape = [total_tokens, n_kv_heads, max(NI_cmp, 1) * BI]

    if scenario != 1:
        raise NotImplementedError(
            "Clean-room reimplementation in progress: only scenario 1 (SWA) is "
            f"available yet; scenario {scenario} (CFA/SCFA) is coming next."
        )

    @tilelang.jit(
        out_idx=[11, 12], workspace_idx=[13, 14, 15, 16, 17], pass_configs=pass_configs
    )
    def _make():
        # =================================================================
        # SWA (scenario 1): sliding-window attention only. Each query
        # position attends to <=128 uncompressed keys = one KV tile, so the
        # whole flash machinery collapses to a single sink-seeded softmax.
        #
        # Each of the ``core_num`` cores walks ITS OWN metadata-assigned query
        # range [linear_start, linear_end) and PIPELINES over those queries
        # (static bound + per-iteration validity guard). Per query the body is
        # a flat op sequence:
        #   Cube  : gather Q + paged KV (L1, two 64-row halves) ; Q@K^T -> ws_score
        #   Vector: scale + window-mask + sink-seeded softmax -> ws_p (GM)
        #   Cube  : P@V (accumulate over the two halves) -> ws_o (GM)
        #   Vector: normalize O / sumexp -> Output ; LSE = ln(sum)+max
        # The TL_ASCEND_AUTO_CV_* passes split this into the Cube and Vector
        # programs, derive the cross-core sync from the ws_* read/write deps,
        # and double-buffer the L1/UB/L0C tiles across pipeline stages -- no
        # manual T.Scope / set_flag / annotate_address.
        # =================================================================
        @T.prim_func
        def sparse_attn_sharedkv_swa(
            Q: T.Tensor(q_shape, dtype),
            ori_KV: T.Tensor(ori_kv_shape, dtype),
            ori_block_table: T.Tensor(ori_bt_shape, indices_dtype),
            cmp_KV: T.Tensor(cmp_kv_shape, dtype),
            cmp_block_table: T.Tensor(cmp_bt_shape, indices_dtype),
            cmp_indices: T.Tensor(indices_shape, indices_dtype),
            q_prefix: T.Tensor([batch], indices_dtype),
            actual_q_len: T.Tensor([batch], indices_dtype),
            actual_kv_len: T.Tensor([batch], indices_dtype),
            Sinks: T.Tensor([n_heads], accum_dtype),
            Metadata: T.Tensor([_SAS_META_SIZE], indices_dtype),
            Output: T.Tensor(out_shape, dtype),
            LSE_out: T.Tensor([total_tokens, n_heads], accum_dtype),
            # ws_kv / ws_acc_o are ABI placeholders (workspace_idx 13 / 17): the
            # single-tile SWA path reads V straight from the L1 KV halves and
            # needs no GM KV-stage or O-accumulator, so neither is referenced in
            # the body. They are kept (a) to preserve api.py's workspace_idx ABI
            # and (b) at their declared shapes -- shrinking a zero-use workspace
            # is a needless allocator risk for a few MB of GM. ws_score/ws_p/ws_o
            # carry ONE slot per core (no ping-pong dim): the compiler
            # double-buffers the L1/UB/L0C tiles across pipeline stages, exactly
            # like both auto-pipeline templates and the paged reference.
            ws_kv: T.Tensor([core_num, 2, BI, D], dtype),
            ws_score: T.Tensor([core_num, H_per_block, BI], accum_dtype),
            ws_p: T.Tensor([core_num, H_per_block, BI], dtype),
            ws_o: T.Tensor([core_num, H_per_block, D], accum_dtype),
            ws_acc_o: T.Tensor([core_num, 2, H_per_block, D], accum_dtype),
        ):
            with T.Kernel(core_num, is_npu=True) as (cid, vid):
                # ---- L1 (cube-side) buffers. ----
                # KV is split into two 64-row halves so each gemm_v0 operand
                # (q_l1 [64,512]=64KB, kv_lo/kv_hi [64,512]=64KB) fits L0A/L0B.
                q_l1 = T.alloc_L1([H_per_block, D], dtype)
                kv_lo = T.alloc_L1([BI_half, D], dtype)
                kv_hi = T.alloc_L1([BI_half, D], dtype)
                # P is staged into two contiguous 64-key halves (p_lo/p_hi) so the
                # PV gemm A-operand is never a strided column slice of one buffer.
                p_lo = T.alloc_L1([H_per_block, BI_half], dtype)
                p_hi = T.alloc_L1([H_per_block, BI_half], dtype)
                # Two L0C score halves (each [64,64] = 16KB) + one wide PV L0C
                # ([64,512] = 128KB) -> 160KB total, byte-identical to the
                # validated num_stages=2 sparse_flash_attn_gqa_pipeline template
                # (acc_s_l0c[64,128] + acc_o_l0c[64,512]).
                acc_s_lo = T.alloc_L0C([H_per_block, BI_half], accum_dtype)
                acc_s_hi = T.alloc_L0C([H_per_block, BI_half], accum_dtype)
                acc_o_l0c = T.alloc_L0C([H_per_block, D], accum_dtype)

                # ---- UB (vector-side) buffers. ----
                acc_o = T.alloc_ub([v_block, D], accum_dtype)
                acc_o_half = T.alloc_ub([v_block, D], dtype)
                acc_s_ub = T.alloc_ub([v_block, BI], accum_dtype)
                acc_s_ub_ = T.alloc_ub([v_block, BI], accum_dtype)
                acc_s_half = T.alloc_ub([v_block, BI], dtype)
                # Online-softmax running state (double-buffered in != out).
                m_i = T.alloc_ub([ub_len], accum_dtype)
                m_i_prev = T.alloc_ub([ub_len], accum_dtype)
                sumexp = T.alloc_ub([ub_len], accum_dtype)
                sumexp_i_ub = T.alloc_ub([ub_len], accum_dtype)
                alpha_exp = T.alloc_ub([ub_len], accum_dtype)
                lse_ub = T.alloc_ub([ub_len], accum_dtype)
                # Per-head sink logits, loaded from GM ONCE before the loop
                # (constant per head; Ascend C's CopySinksIn is also one-shot).
                sinks_ub = T.alloc_ub([ub_len], accum_dtype)
                # Reciprocal of the running sum + its per-row 8-lane broadcast,
                # for the batched output divide (replaces the per-head div loop).
                recip = T.alloc_ub([ub_len], accum_dtype)
                recip_brd8 = T.alloc_ub([v_block, 8], accum_dtype)
                # Window-mask scratch (unconditional createvecindex+compare+select).
                idx_int = T.alloc_ub([BI], indices_dtype)
                idx_float = T.alloc_ub([BI], accum_dtype)
                mask_sel = T.alloc_ub([mask_w], "uint8")
                softmax_tmp = T.alloc_ub([16 * 1024], "uint8")

                # ---- This core's metadata-assigned work range. ----
                # Materialize the loop-invariant scalars ONCE (alloc_var): as
                # plain PrimExprs they re-inline (re-read GM) on every use, which
                # the msprof scalar-pipe profile flagged as the dominant cost.
                # The rebind idiom (alloc_var then `name = <expr>`; use bare name)
                # is the dialect's scalar assignment, validated by
                # test_tilelang_ascend_language_alloc_var.
                meta_base = cid * _FA_METADATA_SIZE
                core_enable = T.alloc_var(indices_dtype, init=0)
                core_enable = Metadata[meta_base + _FA_CORE_ENABLE_INDEX]
                linear_start = T.alloc_var(indices_dtype, init=0)
                linear_start = (
                    Metadata[meta_base + _FA_BN2_START_INDEX] * max_seq
                    + Metadata[meta_base + _FA_M_START_INDEX]
                )
                linear_end = T.alloc_var(indices_dtype, init=0)
                linear_end = (
                    Metadata[meta_base + _FA_BN2_END_INDEX] * max_seq
                    + Metadata[meta_base + _FA_M_END_INDEX]
                )
                # Exact per-core query count (runtime). Looping [0, n_local) over a
                # runtime-bounded T.serial -- with `if valid` INSIDE -- is the
                # validated paged sparse_flash_attn_pa.py shape. (The if-guard lives
                # in a serial loop, NOT inside T.Pipelined: a data-dependent branch
                # inside T.Pipelined segfaults AscendMemoryPlanning under the auto-CV
                # passes; the reference keeps the guard in the serial loop and only
                # pipelines a compile-time inner count.)
                n_local = T.alloc_var(indices_dtype, init=0)
                n_local = T.if_then_else(core_enable != 0, linear_end - linear_start, 0)

                # Load this lane's 32 sink logits once (constant per head).
                T.copy(Sinks[vid * v_block : vid * v_block + v_block], sinks_ub)

                # ---- Walk this core's queries (runtime-bounded serial loop). ----
                # Each iteration is still guarded by `valid` (in-range AND
                # s < act_q) so out-of-range / disabled-core iterations no-op,
                # mirroring sparse_flash_attn_pa.py's `for ... in T.serial(start,
                # end): if s_i < act_q_len:`. The auto-CV passes still split the
                # body into cube/vector programs and sync them across the GM
                # workspaces; cross-query overlap (T.Pipelined) is added next once
                # this compiles + matches numerically.
                for j in T.serial(0, n_local):
                    # ---- Per-query scalars, materialized once (alloc_var). ----
                    pid = T.alloc_var(indices_dtype, init=0)
                    pid = linear_start + j
                    in_range = T.alloc_var("bool", init=False)
                    in_range = T.if_then_else(
                        core_enable != 0,
                        T.if_then_else(pid < linear_end, pid >= linear_start, False),
                        False,
                    )
                    b = T.alloc_var(indices_dtype, init=0)
                    b = T.if_then_else(in_range, pid // max_seq, 0)
                    s = T.alloc_var(indices_dtype, init=0)
                    s = pid % max_seq
                    act_q = T.alloc_var(indices_dtype, init=0)
                    act_q = actual_q_len[b]
                    act_kv = T.alloc_var(indices_dtype, init=0)
                    act_kv = actual_kv_len[b]
                    valid = T.alloc_var("bool", init=False)
                    valid = T.if_then_else(in_range, s < act_q, False)
                    t = T.alloc_var(indices_dtype, init=0)
                    t = q_prefix[b] + s
                    s_global = T.alloc_var(indices_dtype, init=0)
                    s_global = act_kv - act_q + s
                    ori_left = T.alloc_var(indices_dtype, init=0)
                    ori_left = T.if_then_else(
                        s_global < ori_win_left, 0, s_global - ori_win_left
                    )
                    # Paged gather offsets for the two 64-key halves. Each half
                    # is a contiguous 64-key range that crosses at most one page
                    # boundary (ori_block_size >= 128 > 64).
                    bidx_lo = T.alloc_var(indices_dtype, init=0)
                    bidx_lo = ori_left // ori_block_size
                    rowc_lo = T.alloc_var(indices_dtype, init=0)
                    rowc_lo = ori_left % ori_block_size
                    n_lo = T.alloc_var(indices_dtype, init=0)
                    n_lo = ori_block_size - rowc_lo
                    g0_hi = T.alloc_var(indices_dtype, init=0)
                    g0_hi = ori_left + BI_half
                    bidx_hi = T.alloc_var(indices_dtype, init=0)
                    bidx_hi = g0_hi // ori_block_size
                    rowc_hi = T.alloc_var(indices_dtype, init=0)
                    rowc_hi = g0_hi % ori_block_size
                    n_hi = T.alloc_var(indices_dtype, init=0)
                    n_hi = ori_block_size - rowc_hi

                    if valid:
                        # ====================== CUBE: Q@K^T ======================
                        T.copy(Q[t, 0:H_per_block, 0:D], q_l1)
                        # --- Paged sliding-window KV gather (two 64-row halves). ---
                        # Lower half: 64 keys from ori_left. The half spans at most
                        # two contiguous page segments (n_lo rows in block bidx_lo,
                        # remainder in block bidx_lo+1).
                        if n_lo >= BI_half:
                            T.copy(
                                ori_KV[
                                    ori_block_table[b, bidx_lo],
                                    rowc_lo : rowc_lo + BI_half,
                                    0,
                                    :,
                                ],
                                kv_lo[0:BI_half, :],
                            )
                        else:
                            T.copy(
                                ori_KV[
                                    ori_block_table[b, bidx_lo],
                                    rowc_lo : rowc_lo + n_lo,
                                    0,
                                    :,
                                ],
                                kv_lo[0:n_lo, :],
                            )
                            T.copy(
                                ori_KV[
                                    ori_block_table[b, bidx_lo + 1],
                                    0 : BI_half - n_lo,
                                    0,
                                    :,
                                ],
                                kv_lo[n_lo:BI_half, :],
                            )
                        # Upper half: 64 keys from ori_left + 64.
                        if n_hi >= BI_half:
                            T.copy(
                                ori_KV[
                                    ori_block_table[b, bidx_hi],
                                    rowc_hi : rowc_hi + BI_half,
                                    0,
                                    :,
                                ],
                                kv_hi[0:BI_half, :],
                            )
                        else:
                            T.copy(
                                ori_KV[
                                    ori_block_table[b, bidx_hi],
                                    rowc_hi : rowc_hi + n_hi,
                                    0,
                                    :,
                                ],
                                kv_hi[0:n_hi, :],
                            )
                            T.copy(
                                ori_KV[
                                    ori_block_table[b, bidx_hi + 1],
                                    0 : BI_half - n_hi,
                                    0,
                                    :,
                                ],
                                kv_hi[n_hi:BI_half, :],
                            )
                        # Q@K^T over the two 64-key halves -> two L0C halves.
                        T.gemm_v0(q_l1, kv_lo, acc_s_lo, transpose_B=True, init=True)
                        T.gemm_v0(q_l1, kv_hi, acc_s_hi, transpose_B=True, init=True)
                        # Drain L0C scores to the GM workspace (cube -> vector).
                        T.copy(acc_s_lo, ws_score[cid, 0:H_per_block, 0:BI_half])
                        T.copy(acc_s_hi, ws_score[cid, 0:H_per_block, BI_half:BI])

                        # ===================== VECTOR: softmax =====================
                        # This lane reads its 32 heads of the score tile from GM.
                        T.copy(
                            ws_score[cid, vid * v_block : vid * v_block + v_block, :],
                            acc_s_ub_,
                        )
                        # Window mask (unconditional). The loaded 128 keys span
                        # absolute indices [ori_left, ori_left+127]; valid keys are
                        # [ori_left, s_global]. createvecindex seeds idx with
                        # ori_left so idx[k] = ori_left + k, then compare keeps
                        # idx <= s_global (LE). Full window (s_global = ori_left+127)
                        # => all-true => select is a no-op; partial window
                        # (ori_left == 0) masks future keys to -inf. Running the
                        # mask every iteration removes the data-dependent branch
                        # the auto-CV pass would otherwise have to split.
                        T.tile.createvecindex(idx_int, ori_left)
                        T.copy(idx_int, idx_float)
                        T.pipe_barrier("v")
                        T.tile.compare(mask_sel, idx_float, T.float32(s_global), "LE")
                        T.pipe_barrier("v")
                        for h_i in T.serial(v_block):
                            T.tile.select(
                                acc_s_ub[h_i, :],
                                mask_sel,
                                acc_s_ub_[h_i, :],
                                -T.infinity(accum_dtype),
                                "VSEL_TENSOR_SCALAR_MODE",
                            )
                        T.pipe_barrier("v")

                        # Sink-seeded single-tile softmax: seed running max with
                        # the per-head sink logit and the running sum with
                        # exp(0)=1, so the implicit sink token contributes exactly
                        # 1 to sumexp. The sink is seeded in UNSCALED logit space
                        # (scores are multiplied by softmax_scale below), matching
                        # the Ascend C reference swa_block_vector.h and the golden.
                        T.copy(sinks_ub, m_i)
                        T.tile.fill(sumexp, 1.0)
                        T.pipe_barrier("v")
                        T.copy(m_i, m_i_prev)
                        T.tile.mul(acc_s_ub, acc_s_ub, softmax_scale)
                        T.copy(sumexp, sumexp_i_ub)
                        T.tile.softmax_flashv2(
                            acc_s_ub,
                            sumexp,
                            m_i,
                            alpha_exp,
                            sumexp_i_ub,
                            m_i_prev,
                            softmax_tmp,
                            v_block,
                            BI,
                            BI,
                        )
                        # P (= exp(scaled scores - max)) -> ws_p (vector -> cube).
                        T.copy(acc_s_ub, acc_s_half)
                        T.copy(
                            acc_s_half,
                            ws_p[cid, vid * v_block : vid * v_block + v_block, :],
                        )

                        # ====================== CUBE: P@V ======================
                        # Read the full 64-head P tile (both lanes' halves) into
                        # two contiguous L1 halves, then accumulate the 128-key
                        # contraction over the two KV halves (init=True then
                        # init=False) into one [64,512] L0C. Each gemm B-operand
                        # (kv_lo/kv_hi [64,512]=64KB) fits L0B; the A-operand is a
                        # whole contiguous buffer (no strided column slice).
                        T.copy(ws_p[cid, 0:H_per_block, 0:BI_half], p_lo)
                        T.copy(ws_p[cid, 0:H_per_block, BI_half:BI], p_hi)
                        T.gemm_v0(p_lo, kv_lo, acc_o_l0c, init=True)
                        T.gemm_v0(p_hi, kv_hi, acc_o_l0c, init=False)
                        T.copy(acc_o_l0c, ws_o[cid, 0:H_per_block, 0:D])

                        # ================= VECTOR: normalize + LSE =================
                        T.copy(
                            ws_o[cid, vid * v_block : vid * v_block + v_block, :],
                            acc_o,
                        )
                        # Batched normalize O[h, :] /= sumexp[h]: one reciprocal
                        # over all heads, then a per-row broadcast multiply
                        # (brcb + row_muls) -- replaces the per-head div loop.
                        T.tile.reciprocal(recip, sumexp)
                        T.pipe_barrier("v")
                        T.tile.brcb(
                            recip_brd8, recip[0:v_block], (v_block + 7) // 8, 1, 8
                        )
                        T.pipe_barrier("v")
                        T.tile.row_muls(acc_o, acc_o, recip_brd8, v_block, D, D)
                        T.pipe_barrier("v")
                        T.copy(acc_o, acc_o_half)
                        T.copy(
                            acc_o_half,
                            Output[t, vid * v_block : vid * v_block + v_block, :],
                        )
                        # LSE = ln(sum) + max  (sink already folded into both).
                        T.tile.ln(lse_ub, sumexp)
                        T.pipe_barrier("v")
                        T.tile.add(lse_ub, lse_ub, m_i)
                        T.copy(
                            lse_ub[0:v_block],
                            LSE_out[t, vid * v_block : vid * v_block + v_block],
                        )

        return sparse_attn_sharedkv_swa

    if return_prim_func:
        # ``@tilelang.jit`` keeps the original builder under ``__wrapped__``
        # (set by functools.wraps); call it to materialize the raw PrimFunc
        # without triggering the JIT compile / bisheng step.
        return _make.__wrapped__()
    return _make()
